// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC143zXF8btFvuH2n3by0oi7Bpm8jZj3q8',
    appId: '1:819450975342:web:49525ca27dd3b95345c27f',
    messagingSenderId: '819450975342',
    projectId: 'pagbus-5fa1d',
    authDomain: 'pagbus-5fa1d.firebaseapp.com',
    storageBucket: 'pagbus-5fa1d.firebasestorage.app',
    measurementId: 'G-VLPZ5QYPC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDycGo6SaGT6NolzAimFMWIxI-S20KEz0Y',
    appId: '1:819450975342:android:e36d8d503547e8e945c27f',
    messagingSenderId: '819450975342',
    projectId: 'pagbus-5fa1d',
    storageBucket: 'pagbus-5fa1d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLORkfst4zvK8NXIdxsw4G19EO6P7Mvi4',
    appId: '1:819450975342:ios:1fc6e508a8846fda45c27f',
    messagingSenderId: '819450975342',
    projectId: 'pagbus-5fa1d',
    storageBucket: 'pagbus-5fa1d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLORkfst4zvK8NXIdxsw4G19EO6P7Mvi4',
    appId: '1:819450975342:ios:1fc6e508a8846fda45c27f',
    messagingSenderId: '819450975342',
    projectId: 'pagbus-5fa1d',
    storageBucket: 'pagbus-5fa1d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC143zXF8btFvuH2n3by0oi7Bpm8jZj3q8',
    appId: '1:819450975342:web:8158e425e64ada7345c27f',
    messagingSenderId: '819450975342',
    projectId: 'pagbus-5fa1d',
    authDomain: 'pagbus-5fa1d.firebaseapp.com',
    storageBucket: 'pagbus-5fa1d.firebasestorage.app',
    measurementId: 'G-XMC4F3KLJE',
  );
}
